### ISSUE TITLE
Typo in animExporter.c

### ISSUE THREAD

**Issue by zeddy1267** [JaceCear/SA-Trilogy-Animation-Exporter#3]
Line 16 of `animExporter.c`, `#include "arenaAlloc.h"`, has incorrect capitalization (the file is `ArenaAlloc.h`), so it can not compile on case-sensitive filesystems. It should be `#include "ArenaAlloc.h"` I think.

**Comment by JaceCear** [comment]
Sorry, I haven't looked at this repo in ages.

Fixed!
